name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          GATSBY_username: ${{secrets.GATSBY_username}} 
          GATSBY_API_KEY: ${{secrets.GATSBY_API_KEY}} 
