name: Gatsby Publish

on:
#   schedule:
#     - cron: "0 1 * * *"
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GATSBY_username: ${{secrets.GATSBY_username}} 
          GATSBY_API_KEY: ${{secrets.GATSBY_API_KEY}}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
           
